---

include:
  - ./compose-shared.yaml
  - ./backend/world-drive/compose.yaml
  - ./backend/IoT/compose.yaml

services:
  pse-cars-frontend:
    build:
      context: ./frontend/pse-cars
      args:
        - NEXT_PUBLIC_MAPBOX_TOKEN=${NEXT_PUBLIC_MAPBOX_TOKEN}
        - NEXT_PUBLIC_WORLD_DRIVE_HOST=${NEXT_PUBLIC_WORLD_DRIVE_HOST}
    image: pse-cars/frontend
    container_name: pse-cars-frontend
    ports:
      - "80:3000"
    environment:
      - NEXT_PUBLIC_WORLD_DRIVE_HOST=${NEXT_PUBLIC_WORLD_DRIVE_HOST}
      - NEXT_PUBLIC_MAPBOX_TOKEN=${NEXT_PUBLIC_MAPBOX_TOKEN}
      - NEXT_PUBLIC_IOT_URL=${NEXT_PUBLIC_IOT_URL}
    networks:
      - frontend
      - backend # TODO: this should be removed once Kong works
      - default

  pse-cars-backend-configurator:
    build:
      context: ./backend/configurator
    image: pse-cars/backend/configurator

  pse-cars-db-configurator:
    image: postgres:17-alpine
    restart: always
    volumes:
      - db-configurator:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
#      POSTGRES_USER: admin
#      POSTGRES_HOST_AUTH_METHOD: trust

  pse-cars-backend-world-drive:
    build:
      context: ./backend/word-drive
    image: pse-cars/backend/world-drive

  pse-cars-backend-merch:
    build:
      context: ./backend/merch
    image: pse-cars/backend/merch

#  pse-cars-backend-configurator:
#    build:
#      context: ./backend/configurator
#    image: pse-cars/backend/configurator
#
#  pse-cars-backend-merch:
#    build:
#      context: ./backend/merch
#    image: pse-cars/backend/merch
#
#  pse-cars-idp:
#    image: keycloak/keycloak:26.2
#
#  pse-cars-gateway:
#    image: kong:3.9.0-alpine


volumes:
  db-configurator:
    driver: local

secrets: {} # TODO

networks:
  frontend:
