---

include:
  - ./backend/world-drive/compose.yaml # TODO: Refactoring and using include for other modules

services:
  pse-cars-frontend:
    build:
      context: ./frontend/pse-cars
    image: pse-cars/frontend
    ports:
      - "80:3000"
    environment:
      - NEXT_PUBLIC_WORLD_DRIVE_HOST=${NEXT_PUBLIC_WORLD_DRIVE_HOST}
      - NEXT_PUBLIC_MAPBOX_TOKEN=${NEXT_PUBLIC_MAPBOX_TOKEN}

  pse-cars-backend-configurator:
    build:
      context: ./backend/configurator
    image: pse-cars/backend/configurator

  pse-cars-backend-merch:
    build:
      context: ./backend/merch
    image: pse-cars/backend/merch

  pse-cars-backend-iot:
    build:
      context: ./backend/IoT
    image: pse-cars/backend/iot

  pse-cars-idp:
    image: keycloak/keycloak:26.2

  pse-cars-gateway:
    image: kong:3.9.0-alpine

  mosquitto:
    image: eclipse-mosquitto:2.0
    restart: unless-stopped
    container_name: pse-cars-mosquitto
    ports:
      - "1883:1883"   # MQTT protocol
      - "9001:9001"   # MQTT over WebSockets
    volumes:
      - ./backend/mosquitto/config:/mosquitto/config  # your mosquitto.conf here
      - ./backend/mosquitto/data:/mosquitto/data      # persistent message store
      - ./backend/mosquitto/log:/mosquitto/log        # broker logs
    networks:
      - backend

volumes:
  db-configurator:

secrets: {} # TODO

networks:
  backend:
  frontend:
