services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    restart: unless-stopped
    container_name: pse-cars-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./backend/mosquitto/config:/mosquitto/config
      - ./backend/mosquitto/data:/mosquitto/data
      - ./backend/mosquitto/log:/mosquitto/log
    networks:
      - backend
      - world-drive
    healthcheck:
      test: [ "CMD", "sh", "-c", "nc -z localhost 1883" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s


networks:
  backend:
  world-drive:
