---

include:
  - ./compose-shared.yaml
  - ./backend/world-drive/compose.yaml
  - ./backend/IoT/compose.yaml
  - ./backend/configurator/compose.yaml
  - ./backend/merch/compose.yaml

services:
  pse-cars-frontend:
    build:
      context: ./frontend/pse-cars
      args:
        - NEXT_PUBLIC_MAPBOX_TOKEN=${NEXT_PUBLIC_MAPBOX_TOKEN}
        - NEXT_PUBLIC_IOT_URL=http://kong:8000/api/iot
        - NEXT_PUBLIC_SOCKET_URL=http://localhost:3002
        - NEXT_PUBLIC_WORLD_DRIVE_HOST=${NEXT_PUBLIC_WORLD_DRIVE_HOST}
        - NEXT_PUBLIC_MERCH_URL=${NEXT_PUBLIC_MERCH_URL}
    image: pse-cars/frontend
    container_name: pse-cars-frontend
    environment:
      - NEXT_PUBLIC_GATEWAY_URL=http://localhost
      - NEXT_PUBLIC_MAPBOX_TOKEN=${NEXT_PUBLIC_MAPBOX_TOKEN}
      - NEXT_PUBLIC_IOT_URL=${NEXT_PUBLIC_IOT_URL}
      - NEXT_PUBLIC_CONFIGURATOR_BACKEND_HOST=${NEXT_PUBLIC_CONFIGURATOR_BACKEND_HOST}
      - NEXT_PUBLIC_IOT_URL=http://kong:8000/api/iot
      - NEXT_PUBLIC_SOCKET_URL=http://localhost:3002
      - NEXT_PUBLIC_MERCH_URL=${NEXT_PUBLIC_MERCH_URL}
    depends_on:
      - merch-service
    networks:
      - frontend
      - backend
      - merch-network


  kong:
    image: kong:3.9.1
    hostname: kong
    container_name: kong
    environment:
      KONG_DATABASE: "off"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
      KONG_DECLARATIVE_CONFIG: "/opt/kong/kong.yaml"
    command: "kong start"
    ports:
      - "80:8000" # Proxy
      - "443:8443" # Proxy SSL
      - "8001:8001" # Admin API
      - "8444:8444" # Admin API SSL
    volumes:
      - ./config:/opt/kong
    networks:
      - frontend
      - backend
      - default

#  pse-cars-backend-merch:
#    build:
#      context: ./backend/merch
#    image: pse-cars/backend/merch



volumes:
  db-configurator:
    driver: local

secrets: {} # TODO

networks:
  frontend:
  backend:
