include:
  - ../../compose-shared.yaml

services:
  merch-db:
    image: postgres:15-alpine
    container_name: merch-postgres
    environment:
      POSTGRES_DB: merchdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - merch_db_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - merch-network
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d merchdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    command: >
      postgres
      -c shared_preload_libraries='pg_stat_statements'
      -c pg_stat_statements.track=all
      -c max_connections=100
      -c shared_buffers=256MB
      -c effective_cache_size=1GB
      -c maintenance_work_mem=64MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100

  merch-redis:
    image: redis:7-alpine
    container_name: merch-redis
    command: >
      redis-server
      --appendonly yes
      --appendfsync everysec
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --save 900 1
      --save 300 10
      --save 60 10000
    volumes:
      - merch_redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - merch-network
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    sysctls:
      - net.core.somaxconn=65535

  merch-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: merch-service
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: merch-db
      DB_PORT: 5432
      DB_NAME: merchdb
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DDL_AUTO: update
      SHOW_SQL: true
      REDIS_HOST: merch-redis
      REDIS_PORT: 6379
      SERVER_PORT: 8083
      CORS_ORIGINS: ${CORS_ORIGINS}  # FIXED: Now uses environment variable from .env file
      LOG_LEVEL: INFO
      CACHE_LOG_LEVEL: INFO
      SQL_LOG_LEVEL: INFO
      WEB_LOG_LEVEL: INFO
      JAVA_OPTS: "-Xms512m -Xmx1024m -XX:+UseG1GC -XX:G1HeapRegionSize=16m"
    ports:
      - "8083:8083"
    depends_on:
      merch-db:
        condition: service_healthy
      merch-redis:
        condition: service_healthy
    networks:
      - merch-network
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/merch/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - /tmp:/tmp
    deploy:
      resources:
        limits:
          memory: 1.5G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    environment:
      REDIS_HOSTS: merch-redis:merch-redis:6379
      HTTP_USER: admin
      HTTP_PASSWORD: admin123
    ports:
      - "8081:8081"
    networks:
      - merch-network
    depends_on:
      - merch-redis
    profiles:
      - tools

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@psecars.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8082:80"
    networks:
      - merch-network
    depends_on:
      - merch-db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    profiles:
      - tools

volumes:
  merch_db_data:
    driver: local
  merch_redis_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  merch-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16