include:
  - ../../compose-shared.yaml

services:
  world-drive:
    build:
      context: .
    image: pse-cars/backend/world-drive
    container_name: pse-cars-backend-world-drive
    depends_on:
      influxdb:
        condition: service_healthy
      mosquitto: # MQTT service is defined in the shared compose file, since it's used by multiple modules
        condition: service_healthy
    ports:
      - "3001:3001"
    networks:
      - world-drive
      - backend 
    environment:
      - WORLD_DRIVE_INFLUXDB_URL=${WORLD_DRIVE_INFLUXDB_URL}
      - WORLD_DRIVE_INFLUXDB_ADMIN_TOKEN=${WORLD_DRIVE_INFLUXDB_ADMIN_TOKEN}
      - WORLD_DRIVE_INFLUXDB_ORG=${WORLD_DRIVE_INFLUXDB_ORG}
      - WORLD_DRIVE_INFLUXDB_BUCKET=${WORLD_DRIVE_INFLUXDB_BUCKET}
      - MQTT_BROKER_URL=${MQTT_BROKER_URL}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - MQTT_TOPIC=${WORLD_DRIVE_MQTT_TOPIC}

  influxdb:
    image: influxdb:2.7
    container_name: pse-cars-influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    networks:
      - world-drive
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${WORLD_DRIVE_INFLUXDB_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${WORLD_DRIVE_INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${WORLD_DRIVE_INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${WORLD_DRIVE_INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${WORLD_DRIVE_INFLUXDB_ADMIN_TOKEN}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  world-drive-car-position-mock:
    build:
      context: ../car-position-mock
    image: pse-cars/backend/car-position-mock
    container_name: pse-cars-backend-car-position-mock-world-drive
    depends_on:
      mosquitto: # MQTT service is defined in the shared compose file, since it's used by multiple modules
        condition: service_healthy
    networks:
      - world-drive
    environment:
      - MQTT_BROKER_URL=${MQTT_BROKER_URL}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - MQTT_TOPIC=${WORLD_DRIVE_MQTT_TOPIC}
